name: Daily Auto Run (Bun)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run main.ts
        run: bun run main.ts
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_NAME: ${{ vars.EMAIL_NAME }}
